project:
  name: "cu06-deep-ensemble-aves"
  version: "1.0.0"

paths:
  raw_path: "data/raw/"
  folders:
    annotations: "annotations"
    videos: "videos"
    labelframes: "labelframes"
  processed_path: "data/processed/"
  predictions_path: "data/predictions/"
  splits_path: "data/splits/"

raw_files:
  annotations: "ava_train_v2.1.csv"


dataset:
  name: "CBVD-5"
  num_classes: 5
  class_mapping:
    1: 0 # stand -> Class 0
    2: 1 # lying down -> Class 1
    3: 2 # foraging -> Class 2
    4: 3 # drinking water -> Class 3
    5: 4 # rumination -> Class 4
  class_names:
    0: "stand"
    1: "lying_down"
    2: "foraging"
    3: "drinking_water"
    4: "rumination"

model:
  ensemble_type: "stacking"
  base_models: ["DenseNet264", "MobileNetV2", "ResNet50"]

training:
  epochs: 50
  batch_size: 32
